apiVersion: v2
name: auth-svc
description: Colab auth-svc — Authentication + session management
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: svc
    version: "*"
    repository: "file://../../charts/svc"
