/**
 * gateway-svc TypeScript schema — generated by openapi-typescript.
 * DO NOT EDIT MANUALLY. Run `make openapi` to regenerate.
 * Source: packages/api-types/gateway/openapi.json
 */

export interface paths {
  "/healthz": {
    get: operations["healthz"];
  };
  "/ready": {
    get: operations["readyz"];
  };
  "/version": {
    get: operations["version"];
  };
  "/v1/flags": {
    get: operations["getFlags"];
  };
}

export interface components {
  schemas: {
    HealthResponse: {
      status: string;
    };
    ReadyResponse: {
      status: string;
      checks: Record<string, string>;
    };
    VersionResponse: {
      git_sha: string;
      image_tag: string;
      service: string;
    };
    FlagsResponse: {
      ai_mockups_enabled: boolean;
      in_chat_ai_enabled: boolean;
      ads_enabled: boolean;
      marketing_notifications: boolean;
      region_allowlist: string[];
    };
  };
}

export interface operations {
  healthz: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  readyz: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
      503: Record<string, never>;
    };
  };
  version: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
    };
  };
  getFlags: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["FlagsResponse"];
        };
      };
    };
  };
}
