/**
 * hello-svc TypeScript schema — generated by openapi-typescript.
 * DO NOT EDIT MANUALLY. Run `make openapi` to regenerate.
 */

export interface paths {
  "/hello": {
    get: operations["hello"];
  };
  "/healthz": {
    get: operations["healthz"];
  };
}

export interface components {
  schemas: {
    HelloResponse: {
      msg: string;
      env: string;
      request_id: string;
      secret_present: boolean;
    };
    HealthResponse: {
      status: string;
    };
  };
}

export interface operations {
  hello: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HelloResponse"];
        };
      };
    };
  };
  healthz: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
