/**
 * k6 Load Test — Scenario B: Feed Scroll
 *
 * Simulates authenticated users browsing the discovery feed (infinite-scroll
 * and swipe-card mode) with ranking calls.
 *
 * Target: 5,000 VUs steady-state → 7,500 VU spike
 * Pre-requisite: 50,000 synthetic test users pre-seeded in staging DB.
 *
 * Success criteria:
 *   - Redis cache hit rate ≥80% for feed pages during steady state
 *   - discovery-svc pod CPU ≤70% at 5k VUs
 *   - Zero feed pages returning empty results for non-new users
 *
 * Run:
 *   k6 run --env BASE_URL=https://api.staging.colab.test feed-scroll.js
 */

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Counter, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const BASE_URL = __ENV.BASE_URL || 'https://api.staging.colab.test';

// Pre-seeded JWT tokens for 50k test users (generated during T-001 seed step)
// In real execution this file is generated by the seed script.
const TEST_TOKENS = new SharedArray('tokens', function () {
  // Fallback: generate synthetic tokens at runtime (staging accepts signed test JWTs)
  const tokens = [];
  for (let i = 0; i < 50000; i++) {
    tokens.push(`loadtest_token_user_${i}`);
  }
  return tokens;
});

// ---------------------------------------------------------------------------
// Custom metrics
// ---------------------------------------------------------------------------
const feedEmptyRate = new Rate('feed_empty_page_rate');
const cacheHitRate  = new Rate('feed_cache_hit_rate');
const feedErrors    = new Rate('feed_http_error_rate');
const profileFetches = new Counter('feed_profile_detail_fetches');

// ---------------------------------------------------------------------------
// Ramp profile
// ---------------------------------------------------------------------------
export const options = {
  stages: [
    { duration: '5m',  target: 5000 },
    { duration: '20m', target: 5000 },
    { duration: '5m',  target: 7500 },
    { duration: '10m', target: 7500 },
    { duration: '5m',  target: 0 },
  ],
  thresholds: {
    'http_req_duration{name:feed_page_1}':    ['p(95)<300'],
    'http_req_duration{name:feed_page_2}':    ['p(95)<300'],
    'http_req_duration{name:profile_detail}': ['p(95)<200'],
    'http_req_duration{name:feed_save}':      ['p(95)<150'],
    'http_req_duration{name:feed_hide}':      ['p(95)<150'],
    'feed_http_error_rate':                   ['rate<0.01'],
    'http_req_failed':                        ['rate<0.01'],
    'feed_empty_page_rate':                   ['rate<0.001'],
  },
};

// ---------------------------------------------------------------------------
// Main VU scenario
// ---------------------------------------------------------------------------
export default function () {
  const vu = __VU;
  const token = TEST_TOKENS[vu % TEST_TOKENS.length];
  const authHeaders = {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  };

  let profileIds = [];

  group('1_feed_page_1', () => {
    const res = http.get(`${BASE_URL}/discovery/feed?page=1&per_page=20`, {
      headers: authHeaders,
      tags: { name: 'feed_page_1' },
    });
    const ok = check(res, {
      'feed page 1 200': (r) => r.status === 200,
      'feed page 1 non-empty': (r) => {
        try {
          const body = JSON.parse(r.body);
          return Array.isArray(body.profiles) && body.profiles.length > 0;
        } catch { return false; }
      },
    });
    feedErrors.add(res.status >= 400);
    // Check X-Cache header to track Redis cache hits
    const cached = res.headers['X-Cache'] === 'HIT';
    cacheHitRate.add(cached);
    if (ok) {
      try {
        profileIds = JSON.parse(res.body).profiles.map((p) => p.id);
      } catch { /* ignore */ }
      feedEmptyRate.add(profileIds.length === 0);
    }
  });

  sleep(1.5);

  group('2_feed_page_2', () => {
    const res = http.get(`${BASE_URL}/discovery/feed?page=2&per_page=20`, {
      headers: authHeaders,
      tags: { name: 'feed_page_2' },
    });
    check(res, { 'feed page 2 200': (r) => r.status === 200 });
    feedErrors.add(res.status >= 400);
    const cached = res.headers['X-Cache'] === 'HIT';
    cacheHitRate.add(cached);
  });

  sleep(1);

  // Fetch up to 3 profile detail pages (simulate user tapping on a card)
  group('3_profile_details', () => {
    const sampleIds = profileIds.slice(0, 3);
    for (const id of sampleIds) {
      const res = http.get(`${BASE_URL}/discovery/profile/${id}`, {
        headers: authHeaders,
        tags: { name: 'profile_detail' },
      });
      check(res, { 'profile detail 200': (r) => r.status === 200 });
      feedErrors.add(res.status >= 400);
      profileFetches.add(1);
      sleep(0.5);
    }
  });

  // Save one profile
  group('4_save_profile', () => {
    if (profileIds.length === 0) return;
    const saveId = profileIds[0];
    const res = http.post(
      `${BASE_URL}/discovery/save/${saveId}`,
      null,
      { headers: authHeaders, tags: { name: 'feed_save' } },
    );
    check(res, { 'save 200/201': (r) => r.status === 200 || r.status === 201 });
    feedErrors.add(res.status >= 400);
  });

  sleep(0.5);

  // Hide one profile for 3 months
  group('5_hide_profile', () => {
    if (profileIds.length < 2) return;
    const hideId = profileIds[1];
    const res = http.post(
      `${BASE_URL}/discovery/hide/${hideId}`,
      JSON.stringify({ duration_days: 90 }),
      { headers: authHeaders, tags: { name: 'feed_hide' } },
    );
    check(res, { 'hide 200': (r) => r.status === 200 });
    feedErrors.add(res.status >= 400);
  });

  sleep(2);
}
